services:
#    netsf_app_status.example:
#        class: NET\SF\AppStatusBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    netsf_app_status.httpCodeToStringConverterExtension:
        class: NET\SF\AppStatusBundle\Twig\HttpCodeToStringConverterExtension
        tags:
            - { name: twig.extension }
        arguments:
            container: @service_container
